(in-package #:blend2d)

(defun test ()
    (let ((img (autowrap:alloc '%bl:image-core))
          (ctx (autowrap:alloc '%bl:context-core))
          (path (autowrap:alloc '%bl:path-core))
          (origin (autowrap:alloc '%bl:point)))
        (%bl:image-init-as img 800 800 %bl:+format-prgb32+)
        (%bl:context-init-as ctx img (cffi:null-pointer))
        (%bl:path-init path)

        (%bl:context-clear-all ctx)
        (%bl:path-move-to path 26.0d0 31.0d0)
        (%bl:path-cubic-to path 642.0d0 132.0d0 587.0d0 -136.0d0 25.0d0 464.0d0)
        (%bl:path-cubic-to path 882.0d0 404.0d0 144.0d0 267.0d0 27.0d0 31.0d0)
        (%bl:context-set-comp-op ctx %bl:+comp-op-src-over+)
        (%bl:context-set-fill-style-rgba32 ctx #xFFFFFFFF)
        (setf (%bl:point.x origin) 0.0d0)
        (setf (%bl:point.y origin) 0.0d0)
        (%bl:context-fill-path-d ctx origin path)
        (%bl:image-write-to-file img "image.png" (cffi:null-pointer))

        (autowrap:free origin)
        (%bl:path-destroy path)
        (autowrap:free path)
        (%bl:context-destroy ctx)
        (autowrap:free ctx)
        (%bl:image-destroy img)
        (autowrap:free img)))
